use crate::models::{
    factor_info::FactorInfoModel,
    race_result::RaceResultModel,
    skill::SkillModel,
    succession_chara::SuccessionCharaModel,
    succession_history::SuccessionHistoryModel,
    support_card::SupportCardModel,
    trained_chara::{
        KEY_ARRIVE_ROUTE_RACE_ID, KEY_CACHED_CREATE_TS_SOURCE, KEY_CARD_ID, KEY_CHARA_GRADE,
        KEY_CHARA_SEED, KEY_CREATE_TIME, KEY_CREATE_TIME_SOURCE, KEY_FACTOR_ID_ARRAY,
        KEY_FACTOR_INFO_ARRAY, KEY_FANS, KEY_GUTS, KEY_IS_LOCKED, KEY_IS_SAVED, KEY_NICKNAME_ID,
        KEY_NICKNAME_ID_ARRAY, KEY_OWNER_TRAINED_CHARA_ID, KEY_OWNER_VIEWER_ID, KEY_POWER,
        KEY_PROPER_DISTANCE_LONG, KEY_PROPER_DISTANCE_MIDDLE, KEY_PROPER_DISTANCE_MILE,
        KEY_PROPER_DISTANCE_SHORT, KEY_PROPER_GROUND_DIRT, KEY_PROPER_GROUND_TURF,
        KEY_PROPER_RUNNING_STYLE_NIGE, KEY_PROPER_RUNNING_STYLE_OIKOMI,
        KEY_PROPER_RUNNING_STYLE_SASHI, KEY_PROPER_RUNNING_STYLE_SENKO, KEY_RACE_CLOTH_ID,
        KEY_RACE_RESULT_LIST, KEY_RANK, KEY_RANK_SCORE, KEY_RARITY, KEY_REGISTER_TIME,
        KEY_ROUTE_ID, KEY_RUNNING_STYLE, KEY_SCENARIO_ID, KEY_SINGLE_MODE_CHARA_ID,
        KEY_SKILL_ARRAY, KEY_SPEED, KEY_STAMINA, KEY_SUCCESSION_CHARA_ARRAY,
        KEY_SUCCESSION_HISTORY_ARRAY, KEY_SUCCESSION_NUM, KEY_SUPPORT_CARD_LIST, KEY_TALENT_LEVEL,
        KEY_TRAINED_CHARA_ID, KEY_USE_TYPE, KEY_VIEWER_ID, KEY_WINS, KEY_WIN_SADDLE_ID_ARRAY,
        KEY_WIZ,
    },
};
use il2cpp_runtime::{FieldReaderKind, FieldSpec, ModelOffsetCache, RuntimeModelSpec};
use std::sync::LazyLock;

pub struct TrainedCharaDataModel;

static CACHE: LazyLock<ModelOffsetCache> = LazyLock::new(ModelOffsetCache::default);

impl RuntimeModelSpec for TrainedCharaDataModel {
    fn model_name() -> &'static str {
        "TrainedCharaData"
    }

    fn fields() -> &'static [FieldSpec] {
        &[
            FieldSpec {
                key: KEY_VIEWER_ID,
                emit: true,
                required: true,
                candidates: &["_viewerId"],
                reader: FieldReaderKind::ObscuredLongAsI64,
            },
            FieldSpec {
                key: KEY_TRAINED_CHARA_ID,
                emit: true,
                required: true,
                candidates: &["_id"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_OWNER_VIEWER_ID,
                emit: true,
                required: true,
                candidates: &["_ownerViewerId"],
                reader: FieldReaderKind::ObscuredLongAsI64,
            },
            FieldSpec {
                key: KEY_OWNER_TRAINED_CHARA_ID,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_SINGLE_MODE_CHARA_ID,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_CHARA_SEED,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_CARD_ID,
                emit: true,
                required: true,
                candidates: &["_cardId"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_USE_TYPE,
                emit: true,
                required: true,
                candidates: &["_useType"],
                reader: FieldReaderKind::I32AsI64,
            },
            FieldSpec {
                key: KEY_SPEED,
                emit: true,
                required: true,
                candidates: &["_speed"],
                reader: FieldReaderKind::ObscuredInt,
            },
            FieldSpec {
                key: KEY_STAMINA,
                emit: true,
                required: true,
                candidates: &["_stamina"],
                reader: FieldReaderKind::ObscuredInt,
            },
            FieldSpec {
                key: KEY_POWER,
                emit: true,
                required: true,
                candidates: &["_power"],
                reader: FieldReaderKind::ObscuredInt,
            },
            FieldSpec {
                key: KEY_WIZ,
                emit: true,
                required: true,
                candidates: &["_wiz"],
                reader: FieldReaderKind::ObscuredInt,
            },
            FieldSpec {
                key: KEY_GUTS,
                emit: true,
                required: true,
                candidates: &["_guts"],
                reader: FieldReaderKind::ObscuredInt,
            },
            FieldSpec {
                key: KEY_FANS,
                emit: true,
                required: true,
                candidates: &["_fans"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_RANK_SCORE,
                emit: true,
                required: true,
                candidates: &["_rankScore"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_RANK,
                emit: true,
                required: true,
                candidates: &["_rank"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_SCENARIO_ID,
                emit: true,
                required: true,
                candidates: &["<ScenarioId>k__BackingField", "ScenarioId"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_ROUTE_ID,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_ARRIVE_ROUTE_RACE_ID,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_PROPER_GROUND_TURF,
                emit: true,
                required: true,
                candidates: &["_properGroundTurf"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_GROUND_DIRT,
                emit: true,
                required: true,
                candidates: &["_properGroundDirt"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_RUNNING_STYLE_NIGE,
                emit: true,
                required: true,
                candidates: &["_properRunningStyleNige"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_RUNNING_STYLE_SENKO,
                emit: true,
                required: true,
                candidates: &["_properRunningStyleSenko"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_RUNNING_STYLE_SASHI,
                emit: true,
                required: true,
                candidates: &["_properRunningStyleSashi"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_RUNNING_STYLE_OIKOMI,
                emit: true,
                required: true,
                candidates: &["_properRunningStyleOikomi"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_DISTANCE_SHORT,
                emit: true,
                required: true,
                candidates: &["_properDistanceShort"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_DISTANCE_MILE,
                emit: true,
                required: true,
                candidates: &["_properDistanceMile"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_DISTANCE_MIDDLE,
                emit: true,
                required: true,
                candidates: &["_properDistanceMiddle"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_PROPER_DISTANCE_LONG,
                emit: true,
                required: true,
                candidates: &["_properDistanceLong"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_SUCCESSION_NUM,
                emit: true,
                required: true,
                candidates: &["<SuccessionCount>k__BackingField", "SuccessionCount"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_RARITY,
                emit: true,
                required: true,
                candidates: &["<Rarity>k__BackingField", "Rarity"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_IS_SAVED,
                emit: true,
                required: true,
                candidates: &["_isSaved"],
                reader: FieldReaderKind::ObscuredBoolAsI64,
            },
            FieldSpec {
                key: KEY_IS_LOCKED,
                emit: true,
                required: true,
                candidates: &["<IsLock>k__BackingField", "IsLock"],
                reader: FieldReaderKind::ObscuredBoolAsI64,
            },
            FieldSpec {
                key: KEY_TALENT_LEVEL,
                emit: true,
                required: true,
                candidates: &["<TalentLevel>k__BackingField", "TalentLevel"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_RACE_CLOTH_ID,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::ConstantI64(0),
            },
            FieldSpec {
                key: KEY_CHARA_GRADE,
                emit: true,
                required: true,
                candidates: &["<CharaGrade>k__BackingField", "CharaGrade"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_RUNNING_STYLE,
                emit: true,
                required: true,
                candidates: &["_runningStyle"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_NICKNAME_ID,
                emit: true,
                required: true,
                candidates: &["_nickNameId"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_WINS,
                emit: true,
                required: true,
                candidates: &["_singleWinNum"],
                reader: FieldReaderKind::ObscuredIntAsI64,
            },
            FieldSpec {
                key: KEY_CREATE_TIME_SOURCE,
                emit: false,
                required: false,
                candidates: &["<CreateTime>k__BackingField", "_createTime", "createTime"],
                reader: FieldReaderKind::ObscuredString,
            },
            FieldSpec {
                key: KEY_CACHED_CREATE_TS_SOURCE,
                emit: false,
                required: false,
                candidates: &["_cachedCreateTimeTimeStamp", "cachedCreateTimeTimeStamp"],
                reader: FieldReaderKind::ObscuredLongAsI64,
            },
            FieldSpec {
                key: KEY_CREATE_TIME,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::TimestampFrom {
                    string_source_key: KEY_CREATE_TIME_SOURCE,
                    obscured_unix_source_key: KEY_CACHED_CREATE_TS_SOURCE,
                },
            },
            FieldSpec {
                key: KEY_REGISTER_TIME,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::Alias {
                    source_key: KEY_CREATE_TIME,
                },
            },
            FieldSpec {
                key: KEY_SKILL_ARRAY,
                emit: true,
                required: true,
                candidates: &["<AcquiredSkillArray>k__BackingField", "AcquiredSkillArray"],
                reader: FieldReaderKind::PointerArray(SkillModel::read_model_value),
            },
            FieldSpec {
                key: KEY_SUPPORT_CARD_LIST,
                emit: true,
                required: true,
                candidates: &["<SupportCardArray>k__BackingField", "SupportCardArray"],
                reader: FieldReaderKind::PointerArray(SupportCardModel::read_model_value),
            },
            FieldSpec {
                key: KEY_RACE_RESULT_LIST,
                emit: true,
                required: true,
                candidates: &[
                    "<SingleModeRaceResultArray>k__BackingField",
                    "SingleModeRaceResultArray",
                ],
                reader: FieldReaderKind::PointerArray(RaceResultModel::read_model_value),
            },
            FieldSpec {
                key: KEY_WIN_SADDLE_ID_ARRAY,
                emit: true,
                required: true,
                candidates: &["_winSaddleIdArray"],
                reader: FieldReaderKind::ObscuredIntArray,
            },
            FieldSpec {
                key: KEY_NICKNAME_ID_ARRAY,
                emit: true,
                required: true,
                candidates: &["_nickNameIdArray"],
                reader: FieldReaderKind::ObscuredIntArray,
            },
            FieldSpec {
                key: KEY_FACTOR_INFO_ARRAY,
                emit: true,
                required: true,
                candidates: &["<FactorDataArray>k__BackingField", "FactorDataArray"],
                reader: FieldReaderKind::PointerArray(FactorInfoModel::read_model_value),
            },
            FieldSpec {
                key: KEY_FACTOR_ID_ARRAY,
                emit: true,
                required: false,
                candidates: &[],
                reader: FieldReaderKind::FactorIdsFrom {
                    source_key: KEY_FACTOR_INFO_ARRAY,
                },
            },
            FieldSpec {
                key: KEY_SUCCESSION_CHARA_ARRAY,
                emit: true,
                required: true,
                candidates: &[
                    "<SuccessionCharaList>k__BackingField",
                    "SuccessionCharaList",
                ],
                reader: FieldReaderKind::PointerList(SuccessionCharaModel::read_model_value),
            },
            FieldSpec {
                key: KEY_SUCCESSION_HISTORY_ARRAY,
                emit: true,
                required: true,
                candidates: &[
                    "<SuccessionHistoryList>k__BackingField",
                    "SuccessionHistoryList",
                ],
                reader: FieldReaderKind::PointerList(SuccessionHistoryModel::read_model_value),
            },
        ]
    }

    fn cache() -> &'static ModelOffsetCache {
        &CACHE
    }
}
